### PR TITLE
doc: add tech french communities

### PR DESCRIPTION
**Pull request by cchaudier**
Suggesting additions of four more communities:

- DevOps 🇫🇷
- DevOps | SRE
- Numérique responsable 🇫🇷
- Souveraineté numérique 🇫🇷

Split in languages to improve readability

### CODE REVIEW

**Comment by caarlos0** [comment]
Should we maybe split "by country" or "by language"? Wdyt?

**Comment by cchaudier** [comment]
I think its a good Idea.
I'm going to add on commit.

**Comment by cchaudier** [comment]
@caarlos0 it's done

**Comment by caarlos0** [comment]
awesome, thank you!

**Pull request merged**
